In [1]:
#! python
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree, metrics
from sklearn.svm import SVC
import pandas as pd;

sessions = pd.read_csv('all_rounds.csv');

# create training dataset - input and output -- create classes
X = sessions[["t1","t2", "t3", "t4", "speed", "positions"]].to_numpy(); 

y_temp = sessions[["gscore"]];
y_temp.gscore[y_temp.gscore < 13] = 0
y_temp.gscore[y_temp.gscore >= 13] = 1
Y = y_temp.to_numpy();
        
# create training/test dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=2 ); 

svm = SVC(kernel='linear')
svm.fit(X_train, Y_train);  
svm_prediction = svm.predict(X_test); 
print("SVM Accuracy:",metrics.accuracy_score(Y_test, svm_prediction))
print(confusion_matrix(Y_test, svm_prediction)); 
    
# multilayer perceptron classification
mlp = MLPClassifier(activation='logistic', max_iter=5000, solver='lbfgs', hidden_layer_sizes=(2, 5), random_state=42)
mlp.fit(X_train, Y_train)
mlp_prediction = mlp.predict(X_test); 
print("MLP Accuracy:",metrics.accuracy_score(Y_test, mlp_prediction))
print(confusion_matrix(Y_test, mlp_prediction));

# Decision Tree calssification
clf = tree.DecisionTreeClassifier(random_state=10); 
clf.fit(X_train, Y_train)
clf_prediction = clf.predict(X_test)
print("DT Accuracy:",metrics.accuracy_score(Y_test, clf_prediction))
print(confusion_matrix(Y_test, clf_prediction)); 


rf = RandomForestClassifier(n_estimators=150, criterion = 'entropy')
rf.fit(X_train, Y_train)
rf_prediction = rf.predict(X_test)
print("RF Accuracy:",metrics.accuracy_score(Y_test, rf_prediction))
print(confusion_matrix(Y_test, rf_prediction)); 



SVM Accuracy: 0.7628865979381443
[[14 16]
 [ 7 60]]
MLP Accuracy: 0.7525773195876289
[[12 18]
 [ 6 61]]
DT Accuracy: 0.7010309278350515
[[10 20]
 [ 9 58]]
RF Accuracy: 0.7216494845360825
[[10 20]
 [ 7 60]]


/var/folders/ql/c7m8xj6x12d6xlfh52gpq4j80000gn/T/ipykernel_45726/1534644814.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_temp.gscore[y_temp.gscore < 13] = 0
/var/folders/ql/c7m8xj6x12d6xlfh52gpq4j80000gn/T/ipykernel_45726/1534644814.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_temp.gscore[y_temp.gscore >= 13] = 1
/Users/leevi/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/leevi/ana